CREATE TABLE IF NOT EXISTS `supplier_suspend_operations` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
    `card_id` BIGINT NOT NULL COMMENT '卡片ID',
    `supplier_id` BIGINT NULL COMMENT '供应商ID',
    `iccid` VARCHAR(30) NOT NULL COMMENT 'ICCID',
    `msisdn` VARCHAR(20) NULL COMMENT '号码',
    `action` ENUM('suspend', 'resume') NOT NULL COMMENT '操作类型',
    `callback_no` VARCHAR(64) NOT NULL COMMENT '供应商回调单号',
    `request_payload` TEXT NULL COMMENT '请求报文',
    `request_result` TEXT NULL COMMENT '请求结果',
    `callback_payload` TEXT NULL COMMENT '回调报文',
    `callback_code` VARCHAR(32) NULL COMMENT '回调状态码',
    `callback_msg` VARCHAR(255) NULL COMMENT '回调消息',
    `account_status` VARCHAR(32) NULL COMMENT '供应商卡状态',
    `callback_status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '回调状态: pending/success/failed',
    `operator_id` BIGINT NULL COMMENT '操作人ID',
    `completed_at` DATETIME NULL COMMENT '回调完成时间',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` INT DEFAULT 0 COMMENT '删除标记：0=未删除，1=已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_supplier_suspend_operations_callback_no` (`callback_no`),
    KEY `idx_supplier_suspend_operations_card_id` (`card_id`),
    KEY `idx_supplier_suspend_operations_supplier_id` (`supplier_id`),
    KEY `idx_supplier_suspend_operations_iccid` (`iccid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商停复机操作记录';
