[mypy]
python_version = 3.11
ignore_missing_imports = True
plugins = sqlalchemy.ext.mypy.plugin

[mypy-app.db.models.*]
disable_error_code = var-annotated, assignment

[mypy-app.crud.*]
disable_error_code = assignment
